package com.padawanbr.smartsoccer.core.domain.model

enum class TipoTorneio (val tipo: String) {
    ELIMINATORIAS("ELIMINATORIAS"),
    PONTOS_CORRIDOS("PONTOS_CORRIDOS"),
    GRUPOS_E_ELIMINATORIAS("GRUPOS_E_ELIMINATORIAS"),
    PONTOS_CORRIDOS_E_ELIMINATORIAS("PONTOS_CORRIDOS_E_ELIMINATORIAS"),
    GRUPOS_CRUZADOS_E_ELIMINATORIAS("GRUPOS_CRUZADOS_E_ELIMINATORIAS")
}